/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import DAO.FuncionarioDAO;
import DTO.Funcionario;
import java.awt.Button;
import java.awt.FlowLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Date;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author samue
 */
public class CadFunc extends javax.swing.JFrame {

    /**
     * Creates new form CadFunc
     */
    public CadFunc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        JTNomeCompleto2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        JTEmail2 = new javax.swing.JTextField();
        JFTelefone2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JTCidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        JTEstado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        JTBairro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        JTRua = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        JTNumero = new javax.swing.JTextField();
        JFFCEP = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        JL = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JPSenha = new javax.swing.JPasswordField();
        jLabel13 = new javax.swing.JLabel();
        JTsalario = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        JTDtAdimissao = new javax.swing.JTextField();
        JTCargo = new javax.swing.JTextField();
        JTSituacao = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        JBRedefinirCampos = new javax.swing.JButton();
        JBFinalizarCad = new javax.swing.JButton();
        JFFCPF = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Funcionário");
        setPreferredSize(new java.awt.Dimension(960, 700));

        PainelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        PainelPrincipal.setForeground(new java.awt.Color(255, 255, 255));

        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("Nome completo");

        JTNomeCompleto2.setForeground(new java.awt.Color(0, 0, 0));
        JTNomeCompleto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTNomeCompletoActionPerformed(evt);
            }
        });

        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("CPF");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("Telefone");

        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("E-mail");

        JTEmail2.setForeground(new java.awt.Color(0, 0, 0));
        JTEmail2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTEmailActionPerformed(evt);
            }
        });

        JFTelefone2.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTEmail2)
                    .addComponent(JFTelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cidade");

        JTCidade.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Estado");

        JTEstado.setForeground(new java.awt.Color(0, 0, 0));
        JTEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTEstadoActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CEP");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Bairro");

        JTBairro.setForeground(new java.awt.Color(0, 0, 0));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Rua");

        JTRua.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Número");

        JTNumero.setForeground(new java.awt.Color(0, 0, 0));

        JFFCEP.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTRua, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(310, 310, 310)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JFFCEP)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel1)))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFFCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Empresariais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18), new java.awt.Color(0, 0, 0))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        JL.setForeground(new java.awt.Color(0, 0, 0));
        JL.setText("Cargo");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Senha");

        JPSenha.setForeground(new java.awt.Color(0, 0, 0));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Salário");

        JTsalario.setForeground(new java.awt.Color(0, 0, 0));
        JTsalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTsalarioActionPerformed(evt);
            }
        });

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Data de Admissão");

        JTDtAdimissao.setForeground(new java.awt.Color(0, 0, 0));
        JTDtAdimissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTDtAdimissaoActionPerformed(evt);
            }
        });

        JTCargo.setForeground(new java.awt.Color(0, 0, 0));
        JTCargo.setText("\n");

        JTSituacao.setForeground(new java.awt.Color(0, 0, 0));

        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setText("Situacao");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JL, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JTsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(JTDtAdimissao, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(JTSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(266, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JL)
                    .addComponent(jLabel5)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JPSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTDtAdimissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTSituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        JBRedefinirCampos.setForeground(new java.awt.Color(0, 0, 0));
        JBRedefinirCampos.setText("Redefinir Campos/Novo Cadastro");
        JBRedefinirCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBRedefinirCamposActionPerformed(evt);
            }
        });

        JBFinalizarCad.setForeground(new java.awt.Color(0, 0, 0));
        JBFinalizarCad.setText("Finalizar Cadastro");
        JBFinalizarCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBFinalizarCadActionPerformed(evt);
            }
        });

        JFFCPF.setForeground(new java.awt.Color(0, 0, 0));
        JFFCPF.setMaximumSize(new java.awt.Dimension(150, 150));

        jTextField1.setText("jTextField1");

        javax.swing.GroupLayout PainelPrincipalLayout = new javax.swing.GroupLayout(PainelPrincipal);
        PainelPrincipal.setLayout(PainelPrincipalLayout);
        PainelPrincipalLayout.setHorizontalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTNomeCompleto2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(41, 41, 41)
                                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                                        .addComponent(JFFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(82, 82, 82)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(50, 50, 50))
                    .addGroup(PainelPrincipalLayout.createSequentialGroup()
                        .addComponent(JBRedefinirCampos)
                        .addGap(18, 18, 18)
                        .addComponent(JBFinalizarCad)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        PainelPrincipalLayout.setVerticalGroup(
            PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelPrincipalLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTNomeCompleto2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JFFCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBRedefinirCampos)
                    .addComponent(JBFinalizarCad))
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBFinalizarCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBFinalizarCadActionPerformed
        cadastrarFuncionario();
    }//GEN-LAST:event_JBFinalizarCadActionPerformed

    private void JBRedefinirCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBRedefinirCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_JBRedefinirCamposActionPerformed

    private void JTDtAdimissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTDtAdimissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTDtAdimissaoActionPerformed

    private void JTsalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTsalarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTsalarioActionPerformed

    private void JTEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTEstadoActionPerformed

    private void JTNomeCompletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTNomeCompletoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTNomeCompletoActionPerformed

    private void JTEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTEmailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadFunc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadFunc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBFinalizarCad;
    private javax.swing.JButton JBRedefinirCampos;
    private javax.swing.JTextField JFFCEP;
    private javax.swing.JTextField JFFCPF;
    private javax.swing.JTextField JFTelefone;
    private javax.swing.JTextField JFTelefone1;
    private javax.swing.JTextField JFTelefone2;
    private javax.swing.JTextField JFTelefone3;
    private javax.swing.JTextField JFTelefone4;
    private javax.swing.JTextField JFTelefone5;
    private javax.swing.JLabel JL;
    private javax.swing.JPasswordField JPSenha;
    private javax.swing.JTextField JTBairro;
    private javax.swing.JTextField JTCargo;
    private javax.swing.JTextField JTCidade;
    private javax.swing.JTextField JTDtAdimissao;
    private javax.swing.JTextField JTEmail;
    private javax.swing.JTextField JTEmail1;
    private javax.swing.JTextField JTEmail2;
    private javax.swing.JTextField JTEmail3;
    private javax.swing.JTextField JTEmail4;
    private javax.swing.JTextField JTEmail5;
    private javax.swing.JTextField JTEstado;
    private javax.swing.JTextField JTNomeCompleto;
    private javax.swing.JTextField JTNomeCompleto1;
    private javax.swing.JTextField JTNomeCompleto2;
    private javax.swing.JTextField JTNomeCompleto3;
    private javax.swing.JTextField JTNomeCompleto4;
    private javax.swing.JTextField JTNomeCompleto5;
    private javax.swing.JTextField JTNumero;
    private javax.swing.JTextField JTRua;
    private javax.swing.JTextField JTSituacao;
    private javax.swing.JTextField JTsalario;
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
private void cadastrarFuncionario() {
        String nomeCompleto;
        String cpf;
        String email;
        String cargo;
        java.sql.Date dtAdmissao;
        boolean situacao;
        String telefone;
        double salario;
        String senha;
        String cep;
        String rua;
        String cidade;
        int numero;
        String bairro;
        String estado;

        nomeCompleto = JTNomeCompleto2.getText();
        cpf = JFFCPF.getText();
        email = JTEmail2.getText();
        cargo = JTCargo.getText();
        String dataTexto = JTDtAdimissao.getText();
        LocalDate dataLocal = LocalDate.parse(dataTexto);
        long milissegundos = dataLocal.atStartOfDay(ZoneId.systemDefault()).toInstant().toEpochMilli();
        dtAdmissao = new java.sql.Date(milissegundos);
        situacao = Boolean.parseBoolean(JTSituacao.getText());
        telefone = JFTelefone2.getText();
        salario = Double.parseDouble(JTsalario.getText());
        senha = JPSenha.getText();
        cep = JFFCEP.getText();
        rua = JTRua.getText();
        cidade = JTCidade.getText();
        numero = Integer.parseInt(JTNumero.getText());
        bairro = JTBairro.getText();
        estado = JTEstado.getText();

        Funcionario func = new Funcionario();
        func.setBairro(bairro);
        func.setCargo(cargo);
        func.setCep(cep);
        func.setCidade(cidade);
        func.setCpf(cpf);
        func.setDtAdmissao(dtAdmissao);
        func.setEmail(email);
        func.setEstado(estado);
        func.setNomeCompleto(nomeCompleto);
        func.setNumero(numero);
        func.setRua(rua);
        func.setSalario(salario);
        func.setSenha(senha);
        func.setSituacao(situacao);
        func.setTelefone(telefone);

        FuncionarioDAO funcDAO = new FuncionarioDAO();
        funcDAO.cadastrarFuncionario(func);

    }

    public void setNome(String nome) {

        JTNomeCompleto2.setText(nome);
    }

    // Outros métodos e construtores...
    public void setCPF(String texto) {
        JFFCPF.setText(texto);
    }

    public void setEmail(String texto) {
        JTEmail2.setText(texto);
    }

    public void setCargo(String texto) {
        JTCargo.setText(texto);
    }

    public void setDtAdmissao(String texto) {
        JTDtAdimissao.setText(String.valueOf(texto));
    }

    public void setSituacao(String texto) {
        JTSituacao.setText(String.valueOf(texto));
    }

    public void setTelefone(String texto) {
        JFTelefone2.setText(texto);
    }

    public void setSalario(String texto) {
        JTsalario.setText(String.valueOf(texto));
    }

    public void setSenha(String texto) {
        JPSenha.setText(texto);
    }

    public void setCEP(String texto) {
        JFFCEP.setText(texto);
    }

    public void setRua(String texto) {
        JTRua.setText(texto);
    }

    public void setCidade(String texto) {
        JTCidade.setText(texto);
    }

    public void setNumero(String texto) {
        JTNumero.setText(String.valueOf(texto));
    }

    public void setBairro(String texto) {
        JTBairro.setText(texto);
    }

    public void setEstado(String texto) {
        JTEstado.setText(texto);
    }
    
    public void setID(String id){
     jTextField1.setText(id);
    }

    private void limparCampos() {
        JTNomeCompleto.setText("");
        JFFCPF.setText("");
        JTEmail.setText("");
        JTCargo.setText("");
        JTDtAdimissao.setText("");
        JTSituacao.setText("");
        JFTelefone.setText("");
        JTsalario.setText("");
        JPSenha.setText("");
        JFFCEP.setText("");
        JTRua.setText("");
        JTCidade.setText("");
        JTNumero.setText("");
        JTBairro.setText("");
        JTEstado.setText("");
    }

    public void addBotao(JButton botao) {
        PainelPrincipal.add(botao);
        botao.setBounds(400, 634, 150, 27);
        botao.setForeground(new java.awt.Color(0, 0, 0));

        botao.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                int id;
                String nomeCompleto;
                String cpf;
                String email;
                String cargo;
                Date dtAdmissao;
                boolean situacao;
                String telefone;
                double salario;
                String senha;
                String cep;
                String rua;
                String cidade;
                int numero;
                String bairro;
                String estado;

                id = Integer.parseInt(jTextField1.getText());
                nomeCompleto = JTNomeCompleto2.getText();
                cpf = JFFCPF.getText();
                email = JTEmail2.getText();
                cargo = JTCargo.getText();
                String dataTexto = JTDtAdimissao.getText();
                LocalDate dataLocal = LocalDate.parse(dataTexto);
                long milissegundos = dataLocal.atStartOfDay(ZoneId.systemDefault()).toInstant().toEpochMilli();
                dtAdmissao = new java.sql.Date(milissegundos);
                situacao = Boolean.parseBoolean(JTSituacao.getText());
                telefone = JFTelefone2.getText();
                salario = Double.parseDouble(JTsalario.getText());
                senha = JPSenha.getText();
                cep = JFFCEP.getText();
                rua = JTRua.getText();
                cidade = JTCidade.getText();
                numero = Integer.parseInt(JTNumero.getText());
                bairro = JTBairro.getText();
                estado = JTEstado.getText();

                Funcionario func = new Funcionario();
                func.setId(id);
                func.setBairro(bairro);
                func.setCargo(cargo);
                func.setCep(cep);
                func.setCidade(cidade);
                func.setCpf(cpf);
                func.setDtAdmissao(dtAdmissao);
                func.setEmail(email);
                func.setEstado(estado);
                func.setNomeCompleto(nomeCompleto);
                func.setNumero(numero);
                func.setRua(rua);
                func.setSalario(salario);
                func.setSenha(senha);
                func.setSituacao(situacao);
                func.setTelefone(telefone);

                FuncionarioDAO funcDAO = new FuncionarioDAO();
                funcDAO.alterarFuncionario(func);
            }
        });

    }
}
